import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Preview Card Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <main className={styles.cards}>
        <Card bgColor="orange" heading="Sedans" carImg="/images/icon-sedans.svg" para="Choose a sedan for its affordability and excellent fuel economy. Ideal for cruising in the city 
        or on your next road trip." />
        <Card bgColor="cyan" heading="SUVs" carImg="/images/icon-suvs.svg" para="Take an SUV for its spacious interior, power, and versatility. Perfect for your next family vacation 
  and off-road adventures." />
        <Card bgColor="darkcyan" heading="Luxury" carImg="/images/icon-luxury.svg" para="Cruise in the best car brands without the bloated prices. Enjoy the enhanced comfort of a luxury 
  rental and arrive in style." />
      </main>
    </div>
  )
}
